"""Make email unique per outlet

Revision ID: 008c001b6823
Revises: d2e3f4a5b6c7
Create Date: 2026-09-15 20:46:10.521937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008c001b6823'
down_revision: Union[str, None] = 'd2e3f4a5b6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_returns', schema=None) as batch_op:
        batch_op.alter_column('credit_applied',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('debit_applied',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('debt_settled',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('credit_awarded',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('credit_cashed_out',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text('(0.00)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_unique_constraint('uix_user_email_outlet', ['email', 'outlet_id'])
        batch_op.create_index('uix_user_email_superadmin', ['email'], unique=True, postgresql_where=sa.text('outlet_id IS NULL'), sqlite_where=sa.text('outlet_id IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uix_user_email_superadmin', postgresql_where=sa.text('outlet_id IS NULL'), sqlite_where=sa.text('outlet_id IS NULL'))
        batch_op.drop_constraint('uix_user_email_outlet', type_='unique')
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=1)

    with op.batch_alter_table('customer_returns', schema=None) as batch_op:
        batch_op.alter_column('credit_cashed_out',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('credit_awarded',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('debt_settled',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('debit_applied',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))
        batch_op.alter_column('credit_applied',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text('(0.00)'))

    # ### end Alembic commands ###
