"""Add dashboard_reset_time to Outlet

Revision ID: 1dbdddb3940c
Revises: 008c001b6823
Create Date: 2026-09-16 02:03:45.082961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbdddb3940c'
down_revision: Union[str, None] = '008c001b6823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dashboard_reset_time', sa.String(length=5), server_default='00:00', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlets', schema=None) as batch_op:
        batch_op.drop_column('dashboard_reset_time')

    # ### end Alembic commands ###
