"""add_is_void_to_orders

Revision ID: 6becd7303f3c
Revises: a3bbdc86db7c
Create Date: 2026-09-17 02:20:34.438605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6becd7303f3c'
down_revision: Union[str, None] = 'a3bbdc86db7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_void', sa.Boolean(), server_default='false', nullable=False))

    op.execute(
        sa.text(
            "UPDATE orders SET is_void = TRUE WHERE id IN (SELECT replaces_bill_id FROM orders WHERE replaces_bill_id IS NOT NULL) AND status = 'REFUNDED'"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('is_void')

    # ### end Alembic commands ###
