"""add_staff_punch_sessions_table

Revision ID: 9309b4eafa59
Revises: 6becd7303f3c
Create Date: 2026-09-17 21:06:27.926859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9309b4eafa59'
down_revision: Union[str, None] = '6becd7303f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_punch_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('outlet_id', sa.UUID(), nullable=False),
    sa.Column('punch_in_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('punch_out_at', sa.DateTime(), nullable=True),
    sa.Column('auto_punched_out', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name=op.f('fk_staff_punch_sessions_outlet_id_outlets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_staff_punch_sessions_staff_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_punch_sessions'))
    )
    with op.batch_alter_table('staff_punch_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_punch_sessions_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_punch_sessions_punch_in_at'), ['punch_in_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_staff_punch_sessions_staff_id'), ['staff_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_punch_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_punch_sessions_staff_id'))
        batch_op.drop_index(batch_op.f('ix_staff_punch_sessions_punch_in_at'))
        batch_op.drop_index(batch_op.f('ix_staff_punch_sessions_outlet_id'))

    op.drop_table('staff_punch_sessions')
    # ### end Alembic commands ###
