"""add_customer_loyalty_balance_to_orders

Revision ID: a3bbdc86db7c
Revises: 1dbdddb3940c
Create Date: 2026-09-16 11:51:32.460031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3bbdc86db7c'
down_revision: Union[str, None] = '1dbdddb3940c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_loyalty_balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('customer_loyalty_balance')

    # ### end Alembic commands ###
